---
- name: Aseguramos que python esta isntalado
  apt: name=python3-pip state=present update_cache=yes
  tags:
    - boto

- name: Instalamos boyo
  shell: python3 -m pip install -U boto3
  tags:
    - boto
