---
- hosts: siab
  become: yes
  vars_files:
    - vars/apache.yml
    - vars/php.yml
  pre_tasks:
    - name: Set discovered Ansible Python interpreter.
      set_fact:
        ansible_python_interpreter: "/usr/bin/python3"
        when: ansible_python_interpreter is not defined
    - name: Refresh apt cache before package-heavy roles
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"
  roles:
    - deployer
    - common
    - apache
    - apache-config
    - php-versions
    - php
    - php-config
    - mysql
    - redis
    - supervisor
    - swapfile
    - logrotate
